# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accommodation',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('KIT', 'Kirirom Institute Of Technology'), ('VKP', 'Vkirirom Pine Resort'), ('A2A', 'A2A Town Cambodia'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
