# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accommodation',
        ),
    ]
