# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 10:23
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160806_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_cover',
            field=models.ImageField(default='/media/images/default_user_cover_photo_gallaxy.png', upload_to=account.models.handle_upload_cover),
        ),
    ]
