# Generated by Django 2.0.1 on 2018-01-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import src.apps.clothes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Trouser', 'Trouser'), ('Jean', 'Jean'), ('Shock', 'Shock'), ('Towel', 'Towel'), ('Short', 'Short'), ('Jacket', 'Jacket'), ('Blanket', 'Blanket'), ('Skirt', 'Skirt')], max_length=200)),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to=src.apps.clothes.models.handle_upload)),
                ('qrimage', models.ImageField(blank=True, default=None, null=True, upload_to=src.apps.clothes.models.qrcode_location)),
                ('square_image', image_cropping.fields.ImageRatioField('image', '640x640', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='square image')),
                ('is_laundry', models.BooleanField(default=False)),
                ('is_dirty', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaundrySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.Accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrimage', models.ImageField(upload_to=src.apps.clothes.models.handle_upload)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='laundryschedule',
            unique_together={('room', 'day')},
        ),
    ]
