# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('jasmine_hill', 'Jasmine Hill'), ('hotel_container', 'Hotel Container'), ('borey_a', 'Borey A'), ('staff_house', 'Staff House'), ('teacher_building', 'Teacher Building')], max_length=100)),
                ('roomnumber', models.CharField(db_index=True, max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', 'roomnumber'],
            },
        ),
    ]
