# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('jasmine_hill', 'Jasmine Hill'), ('hotel_container', 'Hotel Container'), ('borey_a', 'Borey A'), ('staff_house', 'Staff House'), ('teacher_building', 'Teacher Building')], max_length=200),
        ),
    ]
