# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manageClothes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpye', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Trouser', 'Trouser'), ('Jean', 'Jean'), ('Shock', 'Shock'), ('Towel', 'Towel'), ('Short', 'Short'), ('Jacket', 'Jacket')], max_length=200)),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to=manageClothes.models.handle_upload)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
