# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import manageClothes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Trouser', 'Trouser'), ('Jean', 'Jean'), ('Shock', 'Shock'), ('Towel', 'Towel'), ('Short', 'Short'), ('Jacket', 'Jacket'), ('Blanket', 'Blanket')], max_length=200)),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to=manageClothes.models.handle_upload)),
                ('qrimage', models.ImageField(blank=True, default=None, null=True, upload_to=manageClothes.models.qrcode_location)),
                ('square_image', image_cropping.fields.ImageRatioField('image', '640x640', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='square image')),
                ('is_laundry', models.BooleanField(default=False)),
                ('is_dirty', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrimage', models.ImageField(upload_to=manageClothes.models.handle_upload)),
            ],
        ),
    ]
