# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import manageClothes.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrimage', models.ImageField(upload_to=manageClothes.models.handle_upload)),
            ],
        ),
        migrations.AddField(
            model_name='clothe',
            name='is_laundry',
            field=models.BooleanField(default=False),
        ),
    ]
