# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import manageClothes.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0003_auto_20160803_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='qrimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=manageClothes.models.qrcode_location),
        ),
    ]
