# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import manageClothes.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0005_auto_20160806_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clothe',
            managers=[
                ('objects', manageClothes.models.ClothManager()),
            ],
        ),
        migrations.AlterField(
            model_name='clothe',
            name='type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('trouser', 'Trouser'), ('jean', 'Jean'), ('shock', 'Shock'), ('towel', 'Towel'), ('short', 'Short'), ('jacket', 'Jacket'), ('blanket', 'Blanket')], max_length=200),
        ),
    ]
