# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0006_auto_20160806_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='type',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Trouser', 'Trouser'), ('Jean', 'Jean'), ('Shock', 'Shock'), ('Towel', 'Towel'), ('Short', 'Short'), ('Jacket', 'Jacket'), ('Blanket', 'Blanket')], max_length=200),
        ),
    ]
