# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0007_auto_20160806_2034'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clothe',
            managers=[
            ],
        ),
    ]
