# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 21:49
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0008_auto_20160807_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='square_image',
            field=image_cropping.fields.ImageRatioField('image', '640x640', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='square image'),
        ),
    ]
