# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageClothes', '0009_clothe_square_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
